### ISSUE TITLE
The system test should

### ISSUE THREAD

**Issue by ebolloff** [ontohub/system-test#1]
* [x] clone the repos `backend`, `frontend`, `hets-rabbitmq-wrapper` and `git pull` if already existing
* [x] start rails server
* [x] start ember
* [x] write and run a real test

**Suite (Global)**
* _Before:_ DB create, start rails, start ember, run seeds, git clean
* _After:_ DB drop, stop rails, stop ember

**Test (Each Example/Scenario)**
* _Before:_ PSQL savepoint?
* _After:_ git clean, PSQL savepoint rollback

**Comment by eugenk** [comment]
As for the database problem: We could clone the database after running the seeds and revert it after each example. See http://dba.stackexchange.com/a/3447. 

And we should copy the git repositories to a safe location as well and restore them after each example.

**Comment by jelmd** [comment]
On Solaris one would delegate a zfs to the appropriate users/roles (i.e. make them owner of this FS) and than one would do (assuming pool1/data/pg is the mentioned zfs):
- svcadm disable -s postgres
- zfs snapshot pool1/data/pg@clean
- svcadm enable -s postgres
- run tests
- svcadm disable -s postgres
- zfs rollback pool1/data/pg@clean
- svcadm enable -s postgres

Because there is no time needed for any copies, rollback (as well as snapshots) happen almost instantly (range of ms).

I guess, sooner or later this might be possible on linux as well, so perhaps something to keep in mind.

**Comment by eugenk** [comment]
This poses a problem: Since the Postgres server would be stopped, the connections will be closed as well. As a consequence, we need to restart the rails server, which takes a few seconds. And we need to reset the database state after every single test case.

**Comment by jelmd** [comment]
Ah ok, yes - restarting the db for every single test case is not very smart/takes too much time. 
However, I guess, as long as one is connected to a database, you can't delete it, can you?
Furthermore, if you need the "reset" on every single test case, I assume, the amount of processed data is pretty small. So I guess, just setting a checkpoint, run the test and than rollback to it on db app level should be very fast. No need for extra tools, I would say ... 

BTW: Doesn't rails automatically establish new connections to the DB, if one is needed and none is available [anymore]?

**Comment by eugenk** [comment]
Well, as far as I understand, you suggest using transactions. They won't work in this case, because the data changed since the transaction was started is local to the process and can't be queried from another process. We need the data to be global, though, because the other components of the application (Frontend, Hets, Git-Shell, etc.) need to access it during the test. Basically, what we want to have is something like global transactions.

I'm not really sure whether or not Rails re-establishes the connection after it has been lost. This needs to be tested before implementing the system tests.

**Comment by phyrog** [comment]
The closest thing to global transactions would be what you suggested above with using a database template, IMHO. That's also what is suggested pretty much everywhere where I found this question.

There is one [postgres extension](https://github.com/beaud76/emaj) that tries to handle this, however I am not familiar with pg extensions and don't know if it's usable or not (at least it seems to be actively developed for some years now).

**Comment by jelmd** [comment]
@eugenk - not really "private" TAs, rather a kind of long lived transaction: basically all DBs have a mechanism to flush everything to disk and set a marker, which can be used as a point for recovery later.  So if one could go|roll back to such a marker on the fly, ...
Anyway, what @phyrog found, seems to be close enough to it.
